validation:
  errors:
    mandatory:
      code: "10001"
      message-key: "validation.mandatory"
    min-length:
      code: "10001"
      message-key: "validation.length.min"
    max-length:
      code: "10003"
      message-key: "validation.length.max"
    decimal-min:
      code: "10100"
      message-key: "validation.decimal.min"
    decimal-max:
      code: "10101"
      message-key: "validation.decimal.max"
    decimal-range:
      code: "10102"
      message-key: "validation.decimal.range"
    bad-format:
      code: "10103"
      message-key: "validation.format.invalid"
    bad-value:
      code: "10104"
      message-key: "validation.value.invalid"
    default:
      code: "10199"
      message-key: "validation.default"
  constraint-mappings:
    "NotNull": "mandatory"
    "NotEmpty": "mandatory"
    "NotBlank": "mandatory"
    "Size.min": "min-length"
    "Length.min": "min-length"
    "Size.max": "max-length"
    "Length.max": "max-length"
    "DecimalMin": "decimal-min"
    "DecimalMax": "decimal-max"
    "Range": "decimal-range"
    "Digits": "decimal-range"
    "Pattern": "bad-format"
    "Email": "bad-format"
    "ValueOfEnum": "bad-value"    
